server:
  port: 8082

spring:
  application:
    name: slo-checker

  config:
    import:
      - optional:classpath:rules.yaml

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

slo:
  check-interval: 10s

  metrics:
    refresh-interval: 5s

  prometheus:
    url: http://localhost:9090